DENOMINATIONS = [
    # ── Root ──
    {
        "id": "early-church",
        "name": "Early Church",
        "founded": 33,
        "parent": None,
        "founder": "Jesus of Nazareth & the Apostles",
        "location": "Jerusalem, Roman Judea",
        "adherents": 0,
        "color": "#c9b458",
        "summary": "The original Christian community established at Pentecost, centered on apostolic teaching and the breaking of bread. It spread rapidly across the Roman Empire despite intermittent persecution.",
        "keyDoctrines": ["Apostolic teaching", "Baptism", "Eucharist", "Second Coming of Christ"],
        "scriptureStance": "Old Testament plus apostolic oral tradition; New Testament canon still forming",
        "salvationView": "Faith in the risen Christ, repentance, and baptism"
    },

    # ── Pre-Schism Heterodox Movements ──
    {
        "id": "marcionism",
        "name": "Marcionism",
        "founded": 144,
        "parent": "early-church",
        "founder": "Marcion of Sinope",
        "location": "Rome, Roman Empire",
        "adherents": 0,
        "extinct": True,
        "color": "#888888",
        "summary": "Marcion rejected the Old Testament God as a lesser deity and accepted only edited versions of Luke and Paul's epistles. The movement was declared heretical but persisted for several centuries.",
        "keyDoctrines": ["Rejection of Old Testament", "Dualism between OT and NT God", "Docetism"],
        "scriptureStance": "Edited Gospel of Luke and ten Pauline epistles only",
        "salvationView": "Liberation from the material world of the Old Testament God"
    },
    {
        "id": "montanism",
        "name": "Montanism",
        "founded": 170,
        "parent": "early-church",
        "founder": "Montanus",
        "location": "Phrygia, Asia Minor",
        "adherents": 0,
        "extinct": True,
        "color": "#888888",
        "summary": "An ecstatic prophetic movement emphasizing direct revelation from the Holy Spirit and strict moral discipline. Tertullian, one of the early church's greatest theologians, eventually joined the movement.",
        "keyDoctrines": ["Continuing prophecy", "Strict asceticism", "Imminent Second Coming"],
        "scriptureStance": "Accepted canonical scripture plus new prophetic revelations",
        "salvationView": "Moral rigor and spiritual gifts as evidence of salvation"
    },
    {
        "id": "donatism",
        "name": "Donatism",
        "founded": 311,
        "parent": "early-church",
        "founder": "Donatus Magnus",
        "location": "North Africa",
        "adherents": 0,
        "extinct": True,
        "color": "#888888",
        "summary": "Donatists held that sacraments administered by clergy who had lapsed during persecution were invalid. Augustine of Hippo argued vigorously against them, establishing the principle that sacramental validity doesn't depend on the minister's holiness.",
        "keyDoctrines": ["Purity of clergy required for valid sacraments", "Rebaptism of lapsed Christians"],
        "scriptureStance": "Standard biblical canon",
        "salvationView": "Valid sacraments from morally pure clergy essential for salvation"
    },
    {
        "id": "arianism",
        "name": "Arianism",
        "founded": 320,
        "parent": "early-church",
        "founder": "Arius of Alexandria",
        "location": "Alexandria, Egypt",
        "adherents": 0,
        "extinct": True,
        "color": "#888888",
        "summary": "Arius taught that the Son was a created being, not co-eternal with the Father, prompting the Council of Nicaea in 325 CE. Though condemned, Arianism remained influential among Germanic tribes for centuries.",
        "keyDoctrines": ["Christ as created being", "Subordination of the Son", "Rejection of homoousios"],
        "scriptureStance": "Standard biblical canon with rationalist interpretation",
        "salvationView": "Faith in Christ as the highest created being and moral exemplar"
    },
    {
        "id": "nestorianism",
        "name": "Nestorianism / Church of the East",
        "founded": 431,
        "parent": "early-church",
        "founder": "Nestorius of Constantinople",
        "location": "Persia / Mesopotamia",
        "adherents": 500000,
        "color": "#4a90d9",
        "summary": "After the Council of Ephesus condemned Nestorius's Christology of two separate persons in Christ, his followers established the Church of the East. It became one of the most missionary-active churches in history, reaching China and India.",
        "keyDoctrines": ["Two distinct natures and persons in Christ", "Rejection of Theotokos title for Mary"],
        "scriptureStance": "Peshitta (Syriac Bible) as primary text",
        "salvationView": "Faith in Christ and sacramental participation"
    },
    {
        "id": "monophysitism",
        "name": "Miaphysitism / Oriental Orthodoxy",
        "founded": 451,
        "parent": "early-church",
        "founder": "Dioscorus of Alexandria",
        "location": "Egypt, Ethiopia, Armenia, Syria",
        "adherents": 86000000,
        "color": "#3a6fa5",
        "summary": "After rejecting the Council of Chalcedon's two-nature Christology, these churches maintained that Christ has one united nature (miaphysis) that is both divine and human. They represent some of Christianity's oldest continuous traditions.",
        "keyDoctrines": ["Miaphysite Christology", "One united divine-human nature of Christ"],
        "scriptureStance": "Broader canon including books like Enoch (Ethiopian tradition)",
        "salvationView": "Theosis — union with God through Christ's unified nature"
    },
    {
        "id": "coptic-orthodox",
        "name": "Coptic Orthodox Church",
        "founded": 451,
        "parent": "monophysitism",
        "founder": "Mark the Evangelist (traditional)",
        "location": "Egypt",
        "adherents": 12000000,
        "color": "#3a6fa5",
        "summary": "The Coptic Church traces its founding to the Apostle Mark and is the primary Christian church of Egypt. It has maintained its distinct liturgical tradition, Coptic language, and monastic heritage despite centuries of Islamic rule.",
        "keyDoctrines": ["Miaphysitism", "Apostolic succession from Mark", "Strong monastic tradition"],
        "scriptureStance": "Septuagint-based Old Testament with deuterocanonical books",
        "salvationView": "Theosis through sacraments, particularly the Eucharist"
    },
    {
        "id": "ethiopian-orthodox",
        "name": "Ethiopian Orthodox Tewahedo Church",
        "founded": 340,
        "parent": "early-church",
        "founder": "Frumentius of Axum",
        "location": "Ethiopia",
        "adherents": 49000000,
        "color": "#3a6fa5",
        "summary": "One of the oldest national churches in the world, Ethiopia adopted Christianity in the 4th century. Its unique canon includes 81 books, and it preserves distinctive practices including Sabbath observance and dietary laws.",
        "keyDoctrines": ["Miaphysitism", "Sabbath observance", "Ark of the Covenant tradition"],
        "scriptureStance": "81-book canon including Enoch, Jubilees, and other texts",
        "salvationView": "Theosis and faithful adherence to church law and sacraments"
    },
    {
        "id": "armenian-apostolic",
        "name": "Armenian Apostolic Church",
        "founded": 301,
        "parent": "early-church",
        "founder": "Apostles Bartholomew and Thaddeus (traditional)",
        "location": "Armenia",
        "adherents": 9000000,
        "color": "#3a6fa5",
        "summary": "Armenia was the first nation to adopt Christianity as its state religion in 301 CE. The Armenian Church has been central to national identity, especially through the genocide of 1915 and the preservation of Armenian culture.",
        "keyDoctrines": ["Miaphysitism", "National church identity", "Armenian liturgical rite"],
        "scriptureStance": "Armenian biblical canon with some unique inclusions",
        "salvationView": "Theosis through the sacraments and life of the church"
    },
    {
        "id": "syriac-orthodox",
        "name": "Syriac Orthodox Church",
        "founded": 451,
        "parent": "monophysitism",
        "founder": "Severus of Antioch",
        "location": "Syria, Mesopotamia",
        "adherents": 3000000,
        "color": "#3a6fa5",
        "summary": "The Syriac Orthodox Church preserves the ancient West Syriac liturgical tradition and the Syriac language, closely related to the Aramaic spoken by Jesus. Its scholarship preserved much classical knowledge during the medieval period.",
        "keyDoctrines": ["Miaphysitism", "West Syriac liturgical rite", "Syriac theological tradition"],
        "scriptureStance": "Peshitta and broader Syriac scriptural tradition",
        "salvationView": "Theosis through sacramental life and ascetic discipline"
    },

    # ── Catholic & Orthodox Traditions ──
    {
        "id": "roman-catholicism",
        "name": "Roman Catholicism",
        "founded": 380,
        "parent": "early-church",
        "founder": "Apostle Peter (traditional)",
        "location": "Rome, Italy",
        "adherents": 1380000000,
        "color": "#c0392b",
        "summary": "The Catholic Church traces its authority to Jesus giving Peter the 'keys of the kingdom.' The Edict of Thessalonica (380 CE) established it as the state religion of Rome. The Great Schism of 1054 formalized the break with the Eastern churches.",
        "keyDoctrines": ["Papal supremacy and infallibility", "Transubstantiation", "Marian dogmas", "Seven sacraments", "Purgatory"],
        "scriptureStance": "73-book canon including deuterocanonical books; Scripture and Sacred Tradition as co-equal",
        "salvationView": "Grace through faith and works, mediated by sacraments and the Church"
    },
    {
        "id": "eastern-orthodoxy",
        "name": "Eastern Orthodoxy",
        "founded": 330,
        "parent": "early-church",
        "founder": "Ecumenical Patriarchate of Constantinople",
        "location": "Constantinople (Istanbul), Byzantine Empire",
        "adherents": 220000000,
        "color": "#2471a3",
        "summary": "Eastern Orthodoxy traces its origins to the founding of Constantinople in 330 CE as the center of Eastern Christianity. It understands itself as the continuous, unchanged apostolic church governed by ecumenical councils. The Great Schism of 1054 formalized the break with Rome.",
        "keyDoctrines": ["Conciliarism over papal authority", "Theosis (divinization)", "Essence-energies distinction", "Veneration of icons"],
        "scriptureStance": "Septuagint-based OT plus NT; Holy Tradition as interpretive framework",
        "salvationView": "Theosis — becoming partakers of the divine nature through grace"
    },
    {
        "id": "greek-orthodox",
        "name": "Greek Orthodox Church",
        "founded": 381,
        "parent": "eastern-orthodoxy",
        "founder": "Ecumenical Patriarchate",
        "location": "Greece / Constantinople",
        "adherents": 12000000,
        "color": "#2471a3",
        "summary": "The Greek Orthodox Church holds a position of honor as the 'first among equals' through the Ecumenical Patriarchate of Constantinople. Greek theological and liturgical tradition has shaped all of Orthodoxy profoundly.",
        "keyDoctrines": ["Ecumenical Patriarchate primacy of honor", "Byzantine liturgical tradition", "Patristic theology"],
        "scriptureStance": "Septuagint and Byzantine text tradition",
        "salvationView": "Theosis through liturgical participation and ascetic life"
    },
    {
        "id": "russian-orthodox",
        "name": "Russian Orthodox Church",
        "founded": 988,
        "parent": "eastern-orthodoxy",
        "founder": "Prince Vladimir of Kiev",
        "location": "Russia",
        "adherents": 100000000,
        "color": "#2471a3",
        "summary": "The largest autocephalous Orthodox church, deeply intertwined with Russian national identity since the baptism of Kievan Rus in 988 CE. It survived Soviet persecution and has experienced a major revival since 1991.",
        "keyDoctrines": ["Symphony of church and state", "Slavic liturgical tradition", "Hesychasm"],
        "scriptureStance": "Synodal Russian Bible translation; Church Slavonic liturgical texts",
        "salvationView": "Theosis through sacramental and liturgical life"
    },
    {
        "id": "serbian-orthodox",
        "name": "Serbian Orthodox Church",
        "founded": 1219,
        "parent": "eastern-orthodoxy",
        "founder": "Saint Sava",
        "location": "Serbia",
        "adherents": 12000000,
        "color": "#2471a3",
        "summary": "Autocephaly was established under Saint Sava in 1219, making the Serbian church central to Serbian national identity. It has endured Ottoman occupation, communist rule, and the Yugoslav wars.",
        "keyDoctrines": ["National church identity (Svetosavlje)", "Slavic Orthodox tradition"],
        "scriptureStance": "Standard Orthodox canon in Serbian translation",
        "salvationView": "Theosis through the sacramental life of the church"
    },
    {
        "id": "romanian-orthodox",
        "name": "Romanian Orthodox Church",
        "founded": 1885,
        "parent": "eastern-orthodoxy",
        "founder": "Romanian Orthodox hierarchy",
        "location": "Romania",
        "adherents": 19000000,
        "color": "#2471a3",
        "summary": "The Romanian Orthodox Church is the largest Orthodox church in the European Union and serves as a cornerstone of Romanian national identity. It gained autocephaly in 1885 and patriarchal status in 1925.",
        "keyDoctrines": ["Romanian liturgical tradition", "Patristic theology", "Monastic renewal"],
        "scriptureStance": "Standard Orthodox canon in Romanian translation",
        "salvationView": "Theosis through grace, sacraments, and ascetic effort"
    },
    {
        "id": "bulgarian-orthodox",
        "name": "Bulgarian Orthodox Church",
        "founded": 927,
        "parent": "eastern-orthodoxy",
        "founder": "Bulgarian ecclesiastical hierarchy",
        "location": "Bulgaria",
        "adherents": 8000000,
        "color": "#2471a3",
        "summary": "One of the oldest autocephalous Orthodox churches, recognized as a patriarchate in 927 CE. It played a crucial role in developing the Cyrillic alphabet and Slavic literary culture.",
        "keyDoctrines": ["Cyrillic literary heritage", "Slavic Orthodox liturgical tradition"],
        "scriptureStance": "Standard Orthodox canon; Old Church Slavonic liturgical heritage",
        "salvationView": "Theosis through the sacramental and liturgical life"
    },
    {
        "id": "georgian-orthodox",
        "name": "Georgian Orthodox Church",
        "founded": 337,
        "parent": "eastern-orthodoxy",
        "founder": "Saint Nino",
        "location": "Georgia",
        "adherents": 3500000,
        "color": "#2471a3",
        "summary": "Georgia was one of the earliest nations to adopt Christianity, traditionally in 337 CE through the mission of Saint Nino. The Georgian church maintains its unique liturgical language and ancient monastic tradition.",
        "keyDoctrines": ["Georgian liturgical rite", "Ancient monastic tradition", "National church identity"],
        "scriptureStance": "Georgian biblical translation tradition; one of the oldest Bible translations",
        "salvationView": "Theosis through faith, sacraments, and the life of the church"
    },
    {
        "id": "antiochian-orthodox",
        "name": "Antiochian Orthodox Church",
        "founded": 330,
        "parent": "eastern-orthodoxy",
        "founder": "Apostle Peter (traditional)",
        "location": "Antioch (modern Turkey/Syria), now Damascus",
        "adherents": 4000000,
        "color": "#2471a3",
        "summary": "The Antiochian Church traces its origins to the city where believers were first called Christians. It has been a major vehicle for Orthodox Christianity in the English-speaking world through active outreach and liturgical translation.",
        "keyDoctrines": ["Antiochian liturgical tradition", "Evangelistic outreach", "English-language Orthodoxy"],
        "scriptureStance": "Standard Orthodox canon with Antiochian liturgical tradition",
        "salvationView": "Theosis through sacramental participation and spiritual growth"
    },

    # ── Catholic Religious Orders and Movements ──
    {
        "id": "eastern-catholic",
        "name": "Eastern Catholic Churches",
        "founded": 1595,
        "parent": "roman-catholicism",
        "founder": "Various unions with Rome",
        "location": "Ukraine, Middle East, India, Eastern Europe",
        "adherents": 18000000,
        "color": "#c0392b",
        "summary": "Eastern Catholic churches retain Eastern liturgical traditions while accepting papal authority. The largest is the Ukrainian Greek Catholic Church, which entered union with Rome at the Union of Brest in 1595.",
        "keyDoctrines": ["Papal authority with Eastern liturgy", "Byzantine or other Eastern rites", "Married priesthood permitted"],
        "scriptureStance": "Catholic 73-book canon with Eastern liturgical usage",
        "salvationView": "Catholic soteriology expressed through Eastern liturgical tradition"
    },
    {
        "id": "old-catholic",
        "name": "Old Catholic Church",
        "founded": 1870,
        "parent": "roman-catholicism",
        "founder": "Bishops rejecting Vatican I",
        "location": "Netherlands, Germany, Switzerland",
        "adherents": 500000,
        "color": "#e74c3c",
        "summary": "Old Catholics separated from Rome after rejecting the doctrine of papal infallibility defined at Vatican I in 1870. They maintain apostolic succession and Catholic sacramental theology but with a more conciliar governance.",
        "keyDoctrines": ["Rejection of papal infallibility", "Conciliar governance", "Catholic sacramental theology"],
        "scriptureStance": "Catholic canon; Scripture and Tradition without papal magisterial claims",
        "salvationView": "Catholic sacramental understanding without papal supremacy requirement"
    },

    # ── Protestant Reformation ──
    {
        "id": "lutheranism",
        "name": "Lutheranism",
        "founded": 1517,
        "parent": "roman-catholicism",
        "founder": "Martin Luther",
        "location": "Wittenberg, Germany",
        "adherents": 77000000,
        "color": "#27ae60",
        "summary": "Martin Luther's 95 Theses against indulgences ignited the Protestant Reformation in 1517. Lutheranism emphasizes justification by grace alone through faith alone, as revealed in Scripture alone.",
        "keyDoctrines": ["Sola fide (faith alone)", "Sola gratia (grace alone)", "Sola scriptura", "Consubstantiation", "Two Kingdoms"],
        "scriptureStance": "66-book Protestant canon; Scripture as sole authority (sola scriptura)",
        "salvationView": "Justification by grace alone through faith alone, apart from works"
    },
    {
        "id": "elca",
        "name": "Evangelical Lutheran Church in America",
        "founded": 1988,
        "parent": "lutheranism",
        "founder": "Merger of American Lutheran bodies",
        "location": "United States",
        "adherents": 3300000,
        "color": "#27ae60",
        "summary": "The ELCA formed from a merger of three Lutheran bodies and represents the mainline/progressive wing of American Lutheranism. It ordains women and LGBTQ+ persons and practices full communion with several Protestant denominations.",
        "keyDoctrines": ["Inclusive ordination", "Ecumenical engagement", "Lutheran confessions with progressive interpretation"],
        "scriptureStance": "Historical-critical biblical scholarship; Scripture as witness to Christ",
        "salvationView": "Grace through faith; emphasis on God's unconditional love"
    },
    {
        "id": "lcms",
        "name": "Lutheran Church\u2013Missouri Synod",
        "founded": 1847,
        "parent": "lutheranism",
        "founder": "C.F.W. Walther",
        "location": "United States",
        "adherents": 1800000,
        "color": "#27ae60",
        "summary": "The LCMS is the second-largest Lutheran body in the US, known for its confessional conservatism and emphasis on doctrinal purity. It maintains closed communion and does not ordain women.",
        "keyDoctrines": ["Biblical inerrancy", "Closed communion", "Strict confessional Lutheranism"],
        "scriptureStance": "Biblical inerrancy; Book of Concord as faithful exposition of Scripture",
        "salvationView": "Justification by grace through faith alone; sacramental means of grace"
    },

    # ── Anglicanism ──
    {
        "id": "anglicanism",
        "name": "Anglicanism",
        "founded": 1534,
        "parent": "roman-catholicism",
        "founder": "Henry VIII / Thomas Cranmer",
        "location": "England",
        "adherents": 85000000,
        "color": "#1e8449",
        "summary": "The English Reformation under Henry VIII created a national church that sought a via media between Catholicism and Protestantism. Anglicanism is held together by common prayer, episcopal governance, and the Canterbury communion.",
        "keyDoctrines": ["Via media (middle way)", "Book of Common Prayer", "Episcopacy", "39 Articles", "Three-legged stool: Scripture, Tradition, Reason"],
        "scriptureStance": "Scripture as containing all things necessary for salvation; informed by tradition and reason",
        "salvationView": "Grace through faith; sacramental but Reformed-influenced"
    },
    {
        "id": "church-of-england",
        "name": "Church of England",
        "founded": 1534,
        "parent": "anglicanism",
        "founder": "Henry VIII / Thomas Cranmer",
        "location": "England",
        "adherents": 25000000,
        "color": "#1e8449",
        "summary": "The established church of England with the monarch as Supreme Governor. It encompasses a broad spectrum from Anglo-Catholic to Evangelical, united by the Book of Common Prayer and episcopal order.",
        "keyDoctrines": ["Established church", "Broad church tradition", "Book of Common Prayer", "Episcopal governance"],
        "scriptureStance": "Scripture as primary, interpreted through tradition and reason",
        "salvationView": "Grace through faith; breadth of interpretation from Catholic to Reformed"
    },
    {
        "id": "episcopal-church",
        "name": "Episcopal Church (USA)",
        "founded": 1789,
        "parent": "anglicanism",
        "founder": "Samuel Seabury / American Anglicans",
        "location": "United States",
        "adherents": 1700000,
        "color": "#1e8449",
        "summary": "The American branch of Anglicanism, organized after the Revolution when ties to the Church of England were severed. It has been at the forefront of progressive Christianity, ordaining women (1976) and openly gay bishops (2003).",
        "keyDoctrines": ["Progressive Anglican theology", "Inclusive ordination", "Book of Common Prayer (American)"],
        "scriptureStance": "Scripture interpreted through tradition, reason, and experience (Lambeth Quadrilateral)",
        "salvationView": "Broad soteriology emphasizing God's inclusive love and grace"
    },
    {
        "id": "acna",
        "name": "Anglican Church in North America",
        "founded": 2009,
        "parent": "anglicanism",
        "founder": "Robert Duncan",
        "location": "United States / Canada",
        "adherents": 135000,
        "color": "#1e8449",
        "summary": "ACNA formed as a conservative alternative to the Episcopal Church and Anglican Church of Canada, particularly over issues of sexuality and scriptural authority. It is recognized by many Global South Anglican provinces.",
        "keyDoctrines": ["Biblical authority on sexuality", "Traditional Anglican theology", "Evangelical and Anglo-Catholic streams"],
        "scriptureStance": "Scripture as the final authority in all matters of faith and practice",
        "salvationView": "Justification by grace through faith in Christ alone"
    },

    # ── Reformed / Calvinist Tradition ──
    {
        "id": "calvinism",
        "name": "Calvinism / Reformed Tradition",
        "founded": 1536,
        "parent": "roman-catholicism",
        "founder": "John Calvin",
        "location": "Geneva, Switzerland",
        "adherents": 75000000,
        "color": "#2ecc71",
        "summary": "John Calvin's systematic theology in the Institutes of the Christian Religion established a tradition emphasizing God's absolute sovereignty, predestination, and covenant theology. Reformed churches became dominant in Switzerland, Scotland, the Netherlands, and colonial America.",
        "keyDoctrines": ["TULIP (Five Points of Calvinism)", "Predestination", "Covenant theology", "Regulative principle of worship"],
        "scriptureStance": "Sola scriptura with detailed confessional standards (Westminster, Heidelberg, Belgic)",
        "salvationView": "Unconditional election; irresistible grace; perseverance of the saints"
    },
    {
        "id": "pcusa",
        "name": "Presbyterian Church (USA)",
        "founded": 1983,
        "parent": "calvinism",
        "founder": "Merger of UPCUSA and PCUS",
        "location": "United States",
        "adherents": 1200000,
        "color": "#2ecc71",
        "summary": "The largest Presbyterian body in the US, formed by the 1983 reunion of northern and southern branches. It ordains women and LGBTQ+ persons and takes progressive stances on social issues.",
        "keyDoctrines": ["Reformed theology with progressive interpretation", "Inclusive ordination", "Book of Confessions"],
        "scriptureStance": "Scripture interpreted through the Reformed confessional tradition and contemporary scholarship",
        "salvationView": "Sovereign grace of God; emphasis on God's love for all creation"
    },
    {
        "id": "pca",
        "name": "Presbyterian Church in America",
        "founded": 1973,
        "parent": "calvinism",
        "founder": "Conservative Southern Presbyterians",
        "location": "United States",
        "adherents": 380000,
        "color": "#2ecc71",
        "summary": "The PCA formed when conservative congregations left the mainline Southern Presbyterian church over theological liberalism. It is the largest conservative Reformed denomination in the US, holding to biblical inerrancy.",
        "keyDoctrines": ["Biblical inerrancy", "Westminster Standards", "Complementarian gender roles"],
        "scriptureStance": "Biblical inerrancy; Westminster Confession as subordinate standard",
        "salvationView": "Sovereign grace; unconditional election; definite atonement"
    },
    {
        "id": "christian-reformed",
        "name": "Christian Reformed Church",
        "founded": 1857,
        "parent": "calvinism",
        "founder": "Dutch Reformed immigrants",
        "location": "United States / Canada",
        "adherents": 200000,
        "color": "#2ecc71",
        "summary": "Dutch immigrants who sought stricter Reformed practice than the existing Reformed Church in America founded the CRC. It is known for its intellectual tradition, Christian education system, and neo-Calvinist worldview theology.",
        "keyDoctrines": ["Neo-Calvinism (Kuyperianism)", "Sphere sovereignty", "Common grace", "Cultural mandate"],
        "scriptureStance": "Three Forms of Unity (Belgic Confession, Heidelberg Catechism, Canons of Dort)",
        "salvationView": "Sovereign grace; covenant theology; cultural transformation"
    },
    {
        "id": "dutch-reformed",
        "name": "Dutch Reformed Church",
        "founded": 1571,
        "parent": "calvinism",
        "founder": "Dutch Reformed Synod",
        "location": "Netherlands, South Africa",
        "adherents": 3000000,
        "color": "#2ecc71",
        "summary": "The historic Reformed church of the Netherlands that spread through Dutch colonialism to South Africa, Indonesia, and the Americas. The South African branch controversially provided theological justification for apartheid before repenting in 1986.",
        "keyDoctrines": ["Three Forms of Unity", "Reformed worship", "Covenant theology"],
        "scriptureStance": "Belgic Confession, Heidelberg Catechism, Canons of Dort",
        "salvationView": "Predestination and covenant faithfulness"
    },

    # ── Anabaptism ──
    {
        "id": "anabaptism",
        "name": "Anabaptism",
        "founded": 1525,
        "parent": "roman-catholicism",
        "founder": "Conrad Grebel / Felix Manz",
        "location": "Zurich, Switzerland",
        "adherents": 2000000,
        "color": "#16a085",
        "summary": "The Radical Reformation rejected infant baptism, state-church alliances, and violence, insisting on believers' baptism and separation from worldly power. Anabaptists were persecuted by both Catholics and Protestants.",
        "keyDoctrines": ["Believers' baptism", "Nonresistance / pacifism", "Separation of church and state", "Community of goods"],
        "scriptureStance": "New Testament as primary guide, especially the Sermon on the Mount",
        "salvationView": "Discipleship and following Christ in daily life; believers' baptism as public commitment"
    },
    {
        "id": "mennonite",
        "name": "Mennonite Church",
        "founded": 1536,
        "parent": "anabaptism",
        "founder": "Menno Simons",
        "location": "Netherlands / Northern Germany",
        "adherents": 1500000,
        "color": "#16a085",
        "summary": "Named after Menno Simons, Mennonites emphasize peace, simplicity, and community. The tradition ranges from Old Order groups to progressive urban congregations engaged in social justice and peacebuilding.",
        "keyDoctrines": ["Pacifism", "Simple living", "Community accountability", "Believers' baptism"],
        "scriptureStance": "Scripture as community-interpreted guide for discipleship",
        "salvationView": "Following Christ in daily life; faith expressed through peace and service"
    },
    {
        "id": "amish",
        "name": "Amish",
        "founded": 1693,
        "parent": "anabaptism",
        "founder": "Jakob Ammann",
        "location": "Switzerland / Alsace, now primarily USA",
        "adherents": 380000,
        "color": "#16a085",
        "summary": "Jakob Ammann's stricter interpretation of Anabaptism, emphasizing shunning and plain dress, led to the Amish split from the Mennonites. Old Order Amish maintain horse-and-buggy transportation and limited technology use.",
        "keyDoctrines": ["Ordnung (community rules)", "Meidung (shunning)", "Gelassenheit (yielding to community)", "Plain dress"],
        "scriptureStance": "Bible as interpreted by community tradition and Ordnung",
        "salvationView": "Living faithfully within the community; hope of salvation through obedience"
    },
    {
        "id": "hutterite",
        "name": "Hutterites",
        "founded": 1528,
        "parent": "anabaptism",
        "founder": "Jakob Hutter",
        "location": "Moravia, now primarily Canada/USA",
        "adherents": 50000,
        "color": "#16a085",
        "summary": "Hutterites practice communal living in colonies, sharing all property in common. They are among the most successful communal societies in history, with over 500 colonies across North America.",
        "keyDoctrines": ["Community of goods", "Colony living", "Pacifism", "German dialect preservation"],
        "scriptureStance": "Bible as guide for communal Christian life",
        "salvationView": "Faithful communal life following the pattern of Acts 2"
    },
    {
        "id": "brethren-in-christ",
        "name": "Brethren in Christ",
        "founded": 1778,
        "parent": "anabaptism",
        "founder": "Jacob Engel",
        "location": "Lancaster County, Pennsylvania",
        "adherents": 30000,
        "color": "#16a085",
        "summary": "A unique blend of Anabaptist, Pietist, and Wesleyan traditions, the Brethren in Christ combine peace theology with evangelical revival and holiness teaching. They have transitioned from a rural ethnic group to a diverse evangelical denomination.",
        "keyDoctrines": ["Anabaptist-Pietist-Wesleyan synthesis", "Peace theology", "Holiness", "Community"],
        "scriptureStance": "Scripture as authoritative guide for faith and life",
        "salvationView": "Personal conversion, sanctification, and lived discipleship"
    },

    # ── Puritanism / Congregationalism ──
    {
        "id": "puritanism",
        "name": "Puritanism",
        "founded": 1560,
        "parent": "calvinism",
        "founder": "Thomas Cartwright / William Perkins",
        "location": "England",
        "adherents": 0,
        "extinct": True,
        "color": "#229954",
        "summary": "Puritans sought to purify the Church of England of remaining Catholic practices, insisting on strict Reformed theology and simpler worship. Their emigration to New England profoundly shaped American religion and culture.",
        "keyDoctrines": ["Reformed theology", "Covenant theology", "Purified worship", "Godly commonwealth"],
        "scriptureStance": "Strict sola scriptura with Westminster and Savoy confessions",
        "salvationView": "Calvinist predestination with emphasis on conversion experience"
    },
    {
        "id": "congregationalism",
        "name": "Congregationalism",
        "founded": 1582,
        "parent": "puritanism",
        "founder": "Robert Browne",
        "location": "England, then New England",
        "adherents": 2000000,
        "color": "#229954",
        "summary": "Congregationalists insisted that each local congregation is self-governing under Christ, rejecting both episcopal and presbyterian polity. They were the dominant church in colonial New England and founded Harvard and Yale.",
        "keyDoctrines": ["Local church autonomy", "Covenant ecclesiology", "Reformed theology", "Educated clergy"],
        "scriptureStance": "Scripture interpreted by the gathered congregation under the Holy Spirit",
        "salvationView": "Calvinist soteriology; visible saints model of church membership"
    },

    # ── Baptists ──
    {
        "id": "baptists",
        "name": "Baptist Churches",
        "founded": 1609,
        "parent": "puritanism",
        "founder": "John Smyth / Thomas Helwys",
        "location": "Amsterdam / England",
        "adherents": 100000000,
        "color": "#e67e22",
        "summary": "Baptists emerged from English Separatist Puritanism, insisting on believers' baptism by immersion and religious liberty. They became the largest Protestant family in America, profoundly shaping its religious landscape.",
        "keyDoctrines": ["Believers' baptism by immersion", "Soul competency", "Priesthood of all believers", "Religious liberty", "Local church autonomy"],
        "scriptureStance": "Bible as sole authority; ranges from inerrancy to moderate positions",
        "salvationView": "Personal conversion and faith in Christ; varies from Calvinist to Arminian"
    },
    {
        "id": "sbc",
        "name": "Southern Baptist Convention",
        "founded": 1845,
        "parent": "baptists",
        "founder": "Southern slaveholding Baptists",
        "location": "Augusta, Georgia, USA",
        "adherents": 13000000,
        "color": "#e67e22",
        "summary": "Founded over the issue of slaveholding missionaries, the SBC became the largest Protestant denomination in the US. After a conservative resurgence in the 1980s-90s, it holds firmly to biblical inerrancy and complementarianism.",
        "keyDoctrines": ["Biblical inerrancy (Baptist Faith & Message 2000)", "Complementarianism", "Cooperative Program missions", "Local church autonomy"],
        "scriptureStance": "Total inerrancy and infallibility of Scripture",
        "salvationView": "Personal faith in Christ; once saved, always saved (eternal security)"
    },
    {
        "id": "american-baptist",
        "name": "American Baptist Churches USA",
        "founded": 1907,
        "parent": "baptists",
        "founder": "Northern Baptist Convention",
        "location": "United States",
        "adherents": 1200000,
        "color": "#e67e22",
        "summary": "The mainline counterpart to the SBC, American Baptists are more theologically diverse and progressive. They were among the first Baptist bodies to ordain women and have taken moderate stances on social issues.",
        "keyDoctrines": ["Baptist distinctives with theological diversity", "Social justice emphasis", "Ecumenical engagement"],
        "scriptureStance": "Bible as divinely inspired; range of interpretive approaches",
        "salvationView": "Personal faith in Christ with emphasis on social dimensions of the gospel"
    },
    {
        "id": "ifb",
        "name": "Independent Fundamental Baptists",
        "founded": 1920,
        "parent": "baptists",
        "founder": "Various fundamentalist leaders",
        "location": "United States",
        "adherents": 2500000,
        "color": "#e67e22",
        "summary": "IFB churches are fiercely independent, rejecting all denominational structures and ecumenical cooperation. They are characterized by KJV-only advocacy, strict separation from theological liberals, and aggressive evangelism.",
        "keyDoctrines": ["KJV-only (often)", "Strict separation", "Dispensationalism", "Independent local church"],
        "scriptureStance": "King James Version as the preserved Word of God (many); strict inerrancy",
        "salvationView": "Personal decision to accept Christ; eternal security"
    },
    {
        "id": "free-will-baptist",
        "name": "Free Will Baptists",
        "founded": 1727,
        "parent": "baptists",
        "founder": "Paul Palmer",
        "location": "North Carolina, USA",
        "adherents": 200000,
        "color": "#e67e22",
        "summary": "Free Will Baptists reject Calvinist predestination in favor of Arminian theology, teaching that salvation can be lost. They combine Baptist distinctives with a belief in human free will and the possibility of falling from grace.",
        "keyDoctrines": ["Arminian theology", "Possibility of apostasy", "Believers' baptism", "Foot washing"],
        "scriptureStance": "Bible as infallible Word of God; Arminian interpretation",
        "salvationView": "Free will to accept or reject grace; salvation can be forfeited"
    },
    {
        "id": "primitive-baptist",
        "name": "Primitive Baptists",
        "founded": 1827,
        "parent": "baptists",
        "founder": "Anti-mission Baptists",
        "location": "Southern United States",
        "adherents": 70000,
        "color": "#e67e22",
        "summary": "Primitive Baptists rejected mission societies, Sunday schools, and paid clergy as unbiblical innovations, holding to strict Calvinist predestination. They worship with a cappella singing and maintain a simple, elder-led polity.",
        "keyDoctrines": ["Hyper-Calvinism", "Anti-mission stance", "A cappella worship", "Elder-led governance"],
        "scriptureStance": "Strict sola scriptura; no human innovations beyond Scripture",
        "salvationView": "Unconditional election; God saves whom He wills without human effort"
    },
    {
        "id": "national-baptist",
        "name": "National Baptist Convention",
        "founded": 1886,
        "parent": "baptists",
        "founder": "African American Baptist leaders",
        "location": "United States",
        "adherents": 7500000,
        "color": "#e67e22",
        "summary": "The largest African American denomination, the NBC emerged from the Black church tradition's emphasis on liberation, justice, and communal worship. Martin Luther King Jr. was ordained in this tradition.",
        "keyDoctrines": ["Baptist distinctives", "Liberation theology themes", "Social justice", "Prophetic preaching tradition"],
        "scriptureStance": "Bible as Word of God; emphasis on exodus and liberation narratives",
        "salvationView": "Personal faith in Christ with social transformation as fruit of salvation"
    },

    # ── Methodism ──
    {
        "id": "methodism",
        "name": "Methodism",
        "founded": 1739,
        "parent": "anglicanism",
        "founder": "John Wesley",
        "location": "England",
        "adherents": 80000000,
        "color": "#d35400",
        "summary": "John Wesley's revival movement within Anglicanism emphasized personal holiness, social concern, and the possibility of entire sanctification. Methodism became one of the most successful missionary movements in history.",
        "keyDoctrines": ["Prevenient grace", "Entire sanctification", "Wesleyan Quadrilateral", "Social holiness", "Class meetings"],
        "scriptureStance": "Scripture as primary, interpreted through tradition, reason, and experience (Wesleyan Quadrilateral)",
        "salvationView": "Arminian \u2014 free grace available to all; sanctification as ongoing process"
    },
    {
        "id": "umc",
        "name": "United Methodist Church",
        "founded": 1968,
        "parent": "methodism",
        "founder": "Merger of Methodist and EUB churches",
        "location": "United States (global presence)",
        "adherents": 6500000,
        "color": "#d35400",
        "summary": "The largest Methodist body, the UMC has faced a major schism over LGBTQ+ inclusion, with conservative congregations leaving to form the Global Methodist Church starting in 2022. The remaining UMC has moved in a more progressive direction.",
        "keyDoctrines": ["Wesleyan theology", "Open communion", "Social Principles", "Connectionalism"],
        "scriptureStance": "Wesleyan Quadrilateral; Scripture as primary authority",
        "salvationView": "Grace freely offered to all; faith and works in cooperation"
    },
    {
        "id": "free-methodist",
        "name": "Free Methodist Church",
        "founded": 1860,
        "parent": "methodism",
        "founder": "B.T. Roberts",
        "location": "United States",
        "adherents": 1000000,
        "color": "#d35400",
        "summary": "Founded in protest against pew rental, slavery, and what Roberts saw as spiritual decline in Methodism. Free Methodists emphasize entire sanctification, simplicity, and freedom \u2014 from sin, from slavery, and from secret societies.",
        "keyDoctrines": ["Entire sanctification", "Abolitionism", "Free pews", "Simple worship"],
        "scriptureStance": "Bible as the inspired and inerrant Word of God",
        "salvationView": "Free grace; entire sanctification as second definite work of grace"
    },
    {
        "id": "wesleyan-church",
        "name": "Wesleyan Church",
        "founded": 1968,
        "parent": "methodism",
        "founder": "Merger of Wesleyan Methodist and Pilgrim Holiness churches",
        "location": "United States",
        "adherents": 400000,
        "color": "#d35400",
        "summary": "The Wesleyan Church combines Wesleyan holiness theology with evangelical fervor. It emphasizes entire sanctification, personal piety, and global missions while maintaining conservative theological positions.",
        "keyDoctrines": ["Entire sanctification", "Holiness living", "Evangelical mission", "Egalitarian ministry"],
        "scriptureStance": "Bible as inerrant Word of God; Wesleyan-Arminian interpretation",
        "salvationView": "Prevenient grace, justification, and entire sanctification"
    },
    {
        "id": "ame",
        "name": "African Methodist Episcopal Church",
        "founded": 1816,
        "parent": "methodism",
        "founder": "Richard Allen",
        "location": "Philadelphia, Pennsylvania, USA",
        "adherents": 2500000,
        "color": "#d35400",
        "summary": "Richard Allen founded the AME Church after being pulled from his knees during prayer at a white Methodist church in Philadelphia. It became a powerful institution for African American spiritual, social, and political life.",
        "keyDoctrines": ["Wesleyan theology", "Racial justice", "Social uplift", "Methodist polity"],
        "scriptureStance": "Wesleyan approach to Scripture; emphasis on liberation themes",
        "salvationView": "Free grace and personal conversion with social transformation"
    },
    {
        "id": "ame-zion",
        "name": "AME Zion Church",
        "founded": 1821,
        "parent": "methodism",
        "founder": "James Varick",
        "location": "New York City, USA",
        "adherents": 1400000,
        "color": "#d35400",
        "summary": "Known as the 'Freedom Church' for its strong abolitionist stance, AME Zion provided refuge and support for the Underground Railroad. It was the first Methodist denomination to ordain women and grant them full clergy rights.",
        "keyDoctrines": ["Wesleyan theology", "Abolitionism heritage", "Women's ordination pioneer", "Social justice"],
        "scriptureStance": "Wesleyan Quadrilateral with emphasis on justice and liberation",
        "salvationView": "Free grace available to all; personal and social salvation"
    },
    {
        "id": "nazarene",
        "name": "Church of the Nazarene",
        "founded": 1908,
        "parent": "methodism",
        "founder": "Phineas Bresee",
        "location": "Los Angeles, California, USA",
        "adherents": 2500000,
        "color": "#d35400",
        "summary": "The Church of the Nazarene emerged from the Holiness Movement, synthesizing multiple Wesleyan-holiness groups. It emphasizes entire sanctification as a second definite work of grace and maintains a strong global missions presence.",
        "keyDoctrines": ["Entire sanctification", "Wesleyan-Holiness theology", "Global missions", "Compassionate ministries"],
        "scriptureStance": "Bible as inerrantly revealing the will of God concerning salvation",
        "salvationView": "Prevenient grace, justifying grace, and sanctifying grace (entire sanctification)"
    },
    {
        "id": "salvation-army",
        "name": "The Salvation Army",
        "founded": 1865,
        "parent": "methodism",
        "founder": "William Booth",
        "location": "London, England",
        "adherents": 1700000,
        "color": "#d35400",
        "summary": "William Booth organized his Christian mission along military lines, with uniforms, ranks, and a mission to fight sin and social misery. The Salvation Army is known worldwide for disaster relief, homelessness services, and the iconic red kettles.",
        "keyDoctrines": ["Wesleyan-Holiness theology", "No sacraments", "Military-style governance", "Social service"],
        "scriptureStance": "Bible as the divine rule of Christian faith and practice",
        "salvationView": "Free grace; holiness of heart and life; salvation through faith and repentance"
    },

    # ── Restoration Movement ──
    {
        "id": "restoration-movement",
        "name": "Restoration Movement",
        "founded": 1801,
        "parent": "early-church",
        "founder": "Barton W. Stone / Alexander Campbell",
        "location": "Kentucky / Virginia, USA",
        "adherents": 5000000,
        "color": "#f39c12",
        "summary": "The Stone-Campbell movement sought to restore New Testament Christianity by abandoning all creeds and denominational structures. It produced three major streams that ironically became denominations themselves.",
        "keyDoctrines": ["No creed but Christ", "Restoration of NT church", "Believers' baptism by immersion", "Weekly communion"],
        "scriptureStance": "New Testament as sole blueprint for church faith and practice",
        "salvationView": "Faith, repentance, and baptism for remission of sins"
    },
    {
        "id": "churches-of-christ",
        "name": "Churches of Christ",
        "founded": 1906,
        "parent": "restoration-movement",
        "founder": "Stone-Campbell heritage (conservative)",
        "location": "United States (especially the South)",
        "adherents": 2000000,
        "color": "#f39c12",
        "summary": "The most conservative branch of the Restoration Movement, Churches of Christ insist on a cappella worship, autonomous congregations with no denominational structure, and a strict 'speak where the Bible speaks, silent where it is silent' hermeneutic.",
        "keyDoctrines": ["A cappella worship only", "Autonomous congregations", "Baptismal regeneration", "No instrumental music"],
        "scriptureStance": "Strict New Testament pattern theology; command, example, and necessary inference",
        "salvationView": "Faith, repentance, confession, and baptism by immersion for remission of sins"
    },
    {
        "id": "christian-church",
        "name": "Christian Churches / Churches of Christ",
        "founded": 1927,
        "parent": "restoration-movement",
        "founder": "Stone-Campbell heritage (independent)",
        "location": "United States",
        "adherents": 1200000,
        "color": "#f39c12",
        "summary": "The independent Christian Churches occupy a middle position in the Restoration Movement, using instrumental music but maintaining conservative theology and congregational independence. They are heavily involved in missions and Christian education.",
        "keyDoctrines": ["Congregational autonomy", "Instrumental worship", "Weekly communion", "Believers' baptism"],
        "scriptureStance": "Bible as sole authority; less rigid pattern theology than Churches of Christ",
        "salvationView": "Faith, repentance, and baptism; emphasis on grace"
    },
    {
        "id": "disciples-of-christ",
        "name": "Disciples of Christ",
        "founded": 1968,
        "parent": "restoration-movement",
        "founder": "Stone-Campbell heritage (mainline)",
        "location": "United States",
        "adherents": 400000,
        "color": "#f39c12",
        "summary": "The most progressive branch of the Restoration Movement, the Disciples restructured as a denomination in 1968 while maintaining open communion and congregational freedom. They are active in the ecumenical movement.",
        "keyDoctrines": ["Open communion", "Ecumenism", "Congregational freedom", "Progressive theology"],
        "scriptureStance": "Bible as witness to God's love; historical-critical scholarship welcomed",
        "salvationView": "God's grace freely offered; emphasis on inclusion and social gospel"
    },

    # ── Adventism ──
    {
        "id": "adventism",
        "name": "Adventism",
        "founded": 1844,
        "parent": "baptists",
        "founder": "William Miller",
        "location": "United States",
        "adherents": 25000000,
        "color": "#8e44ad",
        "summary": "The Millerite movement's failed prediction of Christ's return in 1844 (the Great Disappointment) led to several Adventist groups that reinterpreted the prophecy. Seventh-day Adventism became by far the most successful branch.",
        "keyDoctrines": ["Second Coming emphasis", "Sabbatarianism", "Soul sleep", "Investigative judgment"],
        "scriptureStance": "Bible as sole authority; emphasis on prophetic and apocalyptic texts",
        "salvationView": "Faith in Christ with obedience to God's commandments including Sabbath"
    },
    {
        "id": "sda",
        "name": "Seventh-day Adventist Church",
        "founded": 1863,
        "parent": "adventism",
        "founder": "Ellen G. White / Joseph Bates / James White",
        "location": "Battle Creek, Michigan, USA",
        "adherents": 22000000,
        "color": "#8e44ad",
        "summary": "Seventh-day Adventists observe Saturday Sabbath, follow health principles including vegetarianism, and operate one of the largest Protestant educational and healthcare systems in the world. Ellen White's writings are considered prophetic guidance.",
        "keyDoctrines": ["Saturday Sabbath", "Investigative judgment since 1844", "Health message", "Spirit of Prophecy (Ellen White)"],
        "scriptureStance": "Bible as infallible revelation; Ellen White's writings as lesser light pointing to Scripture",
        "salvationView": "Justification by faith; sanctification includes Sabbath-keeping and health laws"
    },
    {
        "id": "branch-davidians",
        "name": "Branch Davidians",
        "founded": 1955,
        "parent": "adventism",
        "founder": "Benjamin Roden (later David Koresh)",
        "location": "Waco, Texas, USA",
        "adherents": 50,
        "extinct": True,
        "color": "#666666",
        "summary": "A splinter group from the Davidian Seventh-day Adventists, they became infamous under David Koresh's leadership and the 1993 siege at their Mount Carmel compound. The group represents a cautionary tale of apocalyptic extremism.",
        "keyDoctrines": ["Koresh as final prophet", "Imminent apocalypse", "Communal living", "Seven Seals interpretation"],
        "scriptureStance": "Bible interpreted through Koresh's prophetic authority",
        "salvationView": "Following God's final messenger (Koresh) through the end times"
    },

    # ── Pentecostalism ──
    {
        "id": "pentecostalism",
        "name": "Pentecostalism",
        "founded": 1901,
        "parent": "methodism",
        "founder": "Charles Parham / William Seymour",
        "location": "Topeka, Kansas / Los Angeles, California, USA",
        "adherents": 280000000,
        "color": "#9b59b6",
        "summary": "Beginning with the Azusa Street Revival in 1906, Pentecostalism emphasizes baptism in the Holy Spirit evidenced by speaking in tongues. It has become the fastest-growing Christian movement in history, especially in the Global South.",
        "keyDoctrines": ["Baptism in the Holy Spirit", "Speaking in tongues (glossolalia)", "Divine healing", "Premillennialism"],
        "scriptureStance": "Bible as inerrant Word of God; experiential hermeneutic",
        "salvationView": "Born-again conversion followed by Spirit baptism as second experience"
    },
    {
        "id": "assemblies-of-god",
        "name": "Assemblies of God",
        "founded": 1914,
        "parent": "pentecostalism",
        "founder": "Hot Springs Assembly of ministers",
        "location": "Hot Springs, Arkansas, USA",
        "adherents": 70000000,
        "color": "#9b59b6",
        "summary": "The largest Pentecostal denomination worldwide, the Assemblies of God combines Pentecostal experience with Trinitarian theology and organizational structure. It has experienced explosive growth in Latin America, Africa, and Asia.",
        "keyDoctrines": ["Initial evidence of tongues", "Four-fold gospel", "Trinitarian Pentecostalism", "Premillennial eschatology"],
        "scriptureStance": "Bible as infallible, authoritative Word of God",
        "salvationView": "Salvation by grace through faith; subsequent Spirit baptism with tongues"
    },
    {
        "id": "cogic",
        "name": "Church of God in Christ (COGIC)",
        "founded": 1897,
        "parent": "methodism",
        "founder": "Charles Harrison Mason",
        "location": "Memphis, Tennessee, USA",
        "adherents": 6500000,
        "color": "#9b59b6",
        "summary": "The largest Pentecostal denomination in the United States and the largest African American Pentecostal body. COGIC combines the Black church tradition of powerful preaching and social concern with classical Pentecostal theology.",
        "keyDoctrines": ["Holiness-Pentecostal theology", "Sanctification", "Spirit baptism with tongues", "Episcopal governance"],
        "scriptureStance": "Bible as inspired and infallible Word of God",
        "salvationView": "Conversion, sanctification, and Spirit baptism as progressive experiences"
    },
    {
        "id": "foursquare",
        "name": "Foursquare Church",
        "founded": 1923,
        "parent": "pentecostalism",
        "founder": "Aimee Semple McPherson",
        "location": "Los Angeles, California, USA",
        "adherents": 8000000,
        "color": "#9b59b6",
        "summary": "Founded by the charismatic evangelist Aimee Semple McPherson, Foursquare is named for its four cardinal doctrines: Jesus as Savior, Baptizer, Healer, and Coming King. McPherson was one of the most famous women in 1920s America.",
        "keyDoctrines": ["Four-fold gospel", "Divine healing", "Spirit baptism", "Premillennialism"],
        "scriptureStance": "Bible as true, immutable, and steadfast Word of God",
        "salvationView": "Personal acceptance of Christ; Spirit baptism; divine healing; Second Coming"
    },
    {
        "id": "upci",
        "name": "United Pentecostal Church International",
        "founded": 1945,
        "parent": "pentecostalism",
        "founder": "Merger of Oneness Pentecostal groups",
        "location": "United States",
        "adherents": 5000000,
        "color": "#7d3c98",
        "summary": "The UPCI is the largest Oneness (non-Trinitarian) Pentecostal denomination, teaching that God is one person (Jesus) manifested in different modes. They practice baptism in Jesus' name only and maintain strict holiness standards.",
        "keyDoctrines": ["Oneness theology (modalism)", "Jesus-name baptism", "Tongues as essential for salvation", "Strict holiness standards"],
        "scriptureStance": "Bible as infallible Word of God; Oneness hermeneutic",
        "salvationView": "Repentance, baptism in Jesus' name, and Spirit baptism with tongues as essential"
    },

    # ── Charismatic Movement ──
    {
        "id": "charismatic-movement",
        "name": "Charismatic Movement",
        "founded": 1960,
        "parent": "pentecostalism",
        "founder": "Dennis Bennett / various leaders",
        "location": "United States (global spread)",
        "adherents": 305000000,
        "color": "#af7ac5",
        "summary": "The Charismatic Renewal brought Pentecostal experiences (tongues, healing, prophecy) into mainline Protestant and Catholic churches starting in the 1960s. Unlike classical Pentecostalism, charismatics often remain in their original denominations.",
        "keyDoctrines": ["Gifts of the Spirit in all denominations", "Praise and worship", "Healing ministry", "Prophetic movement"],
        "scriptureStance": "High view of Scripture combined with emphasis on ongoing revelation",
        "salvationView": "Varies by host denomination; emphasis on Spirit-empowered living"
    },
    {
        "id": "word-of-faith",
        "name": "Word of Faith Movement",
        "founded": 1970,
        "parent": "charismatic-movement",
        "founder": "Kenneth Hagin / Kenneth Copeland",
        "location": "United States",
        "adherents": 10000000,
        "color": "#af7ac5",
        "summary": "The Word of Faith movement teaches that spoken declarations of faith can produce health, wealth, and victory. Critics call it the 'prosperity gospel' for teaching that God promises material abundance to faithful believers.",
        "keyDoctrines": ["Positive confession", "Prosperity gospel", "Seed faith", "Health and wealth"],
        "scriptureStance": "Scripture as collection of divine promises to be claimed by faith",
        "salvationView": "Born-again experience; ongoing faith declarations activate divine promises"
    },
    {
        "id": "vineyard",
        "name": "Vineyard Churches",
        "founded": 1982,
        "parent": "charismatic-movement",
        "founder": "John Wimber",
        "location": "Anaheim, California, USA",
        "adherents": 250000,
        "color": "#af7ac5",
        "summary": "John Wimber's Vineyard movement combined evangelical theology with charismatic practice in a culturally accessible, informal worship style. The Vineyard emphasis on 'power evangelism' and intimate worship influenced churches far beyond its own network.",
        "keyDoctrines": ["Power evangelism", "Signs and wonders", "Kingdom theology", "Contemporary worship"],
        "scriptureStance": "Evangelical with openness to continuing revelation through the Spirit",
        "salvationView": "Personal faith in Christ; empowered by the Spirit for kingdom ministry"
    },
    {
        "id": "ihop",
        "name": "International House of Prayer",
        "founded": 1999,
        "parent": "charismatic-movement",
        "founder": "Mike Bickle",
        "location": "Kansas City, Missouri, USA",
        "adherents": 10000,
        "color": "#af7ac5",
        "summary": "IHOP-KC maintains a 24/7 prayer and worship model, combining charismatic spirituality with contemplative prayer and prophetic emphasis. The organization has faced significant controversy and leadership scandals.",
        "keyDoctrines": ["24/7 prayer and worship", "Bridal paradigm", "Prophetic ministry", "Contemplative-charismatic fusion"],
        "scriptureStance": "Scripture as primary with strong emphasis on Song of Solomon allegory and prophetic books",
        "salvationView": "Personal relationship with Jesus as Bridegroom; Spirit-filled devotion"
    },
    {
        "id": "nar",
        "name": "New Apostolic Reformation",
        "founded": 1996,
        "parent": "charismatic-movement",
        "founder": "C. Peter Wagner",
        "location": "United States (global network)",
        "adherents": 3000000,
        "color": "#af7ac5",
        "summary": "The NAR teaches that God is restoring the offices of apostle and prophet to govern the church today. It has been influential in charismatic and political circles, advocating for '7 Mountain Mandate' cultural dominion.",
        "keyDoctrines": ["Modern apostles and prophets", "Seven Mountain Mandate", "Dominion theology", "Spiritual warfare"],
        "scriptureStance": "Scripture plus continuing apostolic and prophetic revelation",
        "salvationView": "Born-again conversion; Spirit empowerment for cultural dominion"
    },

    # ── Quakerism ──
    {
        "id": "quakers",
        "name": "Religious Society of Friends (Quakers)",
        "founded": 1647,
        "parent": "puritanism",
        "founder": "George Fox",
        "location": "England",
        "adherents": 380000,
        "color": "#1abc9c",
        "summary": "George Fox taught that every person has direct access to God through the 'Inner Light,' rendering clergy, sacraments, and formal liturgy unnecessary. Quakers became known for pacifism, simplicity, and social justice activism.",
        "keyDoctrines": ["Inner Light", "No ordained clergy", "Silent worship", "Peace testimony", "Equality of all persons"],
        "scriptureStance": "Inner Light as primary; Scripture as secondary witness",
        "salvationView": "Responding to the Inner Light of Christ present in every person"
    },

    # ── Heterodox / Restorationist Groups ──
    {
        "id": "mormonism",
        "name": "Mormonism / Latter-day Saints",
        "founded": 1830,
        "parent": "early-church",
        "founder": "Joseph Smith Jr.",
        "location": "Fayette, New York, USA",
        "adherents": 17000000,
        "color": "#7f8c8d",
        "summary": "Joseph Smith claimed angelic visitations and translated the Book of Mormon from golden plates. The LDS Church teaches a restored gospel, temple ordinances, and a unique cosmology where humans can become like God.",
        "keyDoctrines": ["Book of Mormon", "Temple ordinances", "Exaltation (becoming like God)", "Living prophet", "Plan of Salvation"],
        "scriptureStance": "Bible (as far as correctly translated), Book of Mormon, D&C, Pearl of Great Price",
        "salvationView": "Universal resurrection; exaltation through faith, repentance, baptism, temple ordinances"
    },
    {
        "id": "community-of-christ",
        "name": "Community of Christ (RLDS)",
        "founded": 1860,
        "parent": "mormonism",
        "founder": "Joseph Smith III",
        "location": "Independence, Missouri, USA",
        "adherents": 250000,
        "color": "#7f8c8d",
        "summary": "Originally the Reorganized LDS Church, led by Joseph Smith's son. It has moved toward mainstream Christianity, ordaining women (1984) and LGBTQ+ persons, and de-emphasizing uniquely Mormon doctrines like temple work and exaltation.",
        "keyDoctrines": ["Peace and justice", "Progressive revelation", "Open canon", "Inclusive community"],
        "scriptureStance": "Bible, Book of Mormon, and Doctrine & Covenants (different edition from LDS)",
        "salvationView": "Grace through faith; emphasis on discipleship and community"
    },
    {
        "id": "flds",
        "name": "Fundamentalist LDS (FLDS)",
        "founded": 1930,
        "parent": "mormonism",
        "founder": "Various fundamentalist Mormon leaders",
        "location": "Colorado City, Arizona / Hildale, Utah, USA",
        "adherents": 10000,
        "color": "#666666",
        "summary": "FLDS groups continue practicing polygamy and other 19th-century Mormon doctrines abandoned by the mainstream LDS Church. The group under Warren Jeffs became notorious for criminal abuses and authoritarian control.",
        "keyDoctrines": ["Plural marriage", "United Order (communal living)", "19th-century Mormon doctrine preservation"],
        "scriptureStance": "Early LDS scriptures and teachings; rejection of post-1890 LDS developments",
        "salvationView": "Exaltation through plural marriage and strict obedience to the prophet"
    },
    {
        "id": "kingston-group",
        "name": "Kingston Group (Davis County Cooperative)",
        "founded": 1935,
        "parent": "mormonism",
        "founder": "Charles Elden Kingston",
        "location": "Salt Lake City, Utah, USA",
        "adherents": 3500,
        "color": "#666666",
        "summary": "A secretive polygamist fundamentalist Mormon group controlling significant business assets. The Kingston Group practices plural marriage, communal economics, and maintains strict separation from mainstream society.",
        "keyDoctrines": ["Plural marriage", "Communal economics", "Blood atonement", "Racial purity"],
        "scriptureStance": "Early LDS scriptures with unique Kingston interpretations",
        "salvationView": "Exaltation through plural marriage and obedience to group leadership"
    },
    {
        "id": "jehovahs-witnesses",
        "name": "Jehovah's Witnesses",
        "founded": 1870,
        "parent": "adventism",
        "founder": "Charles Taze Russell",
        "location": "Pittsburgh, Pennsylvania, USA",
        "adherents": 8700000,
        "color": "#7f8c8d",
        "summary": "The Watch Tower Society teaches that Jehovah is God's true name, Jesus is the archangel Michael, and only 144,000 will go to heaven. Known for door-to-door evangelism, refusal of blood transfusions, and political neutrality.",
        "keyDoctrines": ["Jehovah as God's name", "Jesus as Michael the archangel", "144,000 anointed class", "No blood transfusions", "No holidays/birthdays"],
        "scriptureStance": "New World Translation as most accurate Bible; Governing Body as interpreter",
        "salvationView": "Faith demonstrated by works and preaching; most saved to paradise earth, 144,000 to heaven"
    },
    {
        "id": "christian-science",
        "name": "Christian Science",
        "founded": 1879,
        "parent": "congregationalism",
        "founder": "Mary Baker Eddy",
        "location": "Boston, Massachusetts, USA",
        "adherents": 100000,
        "color": "#95a5a6",
        "summary": "Mary Baker Eddy taught that matter and sickness are illusions of mortal mind, and that spiritual understanding of God as infinite Mind brings healing. Christian Scientists typically rely on prayer rather than medicine.",
        "keyDoctrines": ["Unreality of matter and sickness", "God as infinite Mind", "Spiritual healing", "Science and Health with Key to the Scriptures"],
        "scriptureStance": "Bible interpreted through Science and Health by Mary Baker Eddy",
        "salvationView": "Progressive spiritual understanding; overcoming the illusion of material existence"
    },
    {
        "id": "unity-church",
        "name": "Unity Church",
        "founded": 1889,
        "parent": "congregationalism",
        "founder": "Charles and Myrtle Fillmore",
        "location": "Kansas City, Missouri, USA",
        "adherents": 100000,
        "color": "#95a5a6",
        "summary": "Unity is a New Thought movement teaching that God is an omnipresent energy and that positive thinking and affirmation can transform one's life. It draws from Christianity but diverges significantly from orthodox theology.",
        "keyDoctrines": ["God as universal energy", "Christ consciousness in all people", "Positive affirmation", "Reincarnation"],
        "scriptureStance": "Bible as metaphorical and symbolic; multiple valid spiritual paths",
        "salvationView": "Spiritual evolution through Christ consciousness; no hell or damnation"
    },

    # ── Modern Movements ──
    {
        "id": "progressive-christianity",
        "name": "Progressive Christianity",
        "founded": 1990,
        "parent": "congregationalism",
        "founder": "Various liberal theologians",
        "location": "United States / Europe",
        "adherents": 5000000,
        "color": "#bdc3c7",
        "summary": "Progressive Christianity is a post-liberal movement emphasizing social justice, inclusivity, and reinterpretation of traditional doctrines. It questions substitutionary atonement, biblical inerrancy, and exclusivist salvation claims.",
        "keyDoctrines": ["Social justice", "LGBTQ+ full inclusion", "Environmental stewardship", "Interfaith dialogue", "Post-substitutionary atonement"],
        "scriptureStance": "Bible as human witness to divine encounters; non-literal, contextual interpretation",
        "salvationView": "Broad and inclusive; salvation as wholeness and justice rather than afterlife destination"
    },
    {
        "id": "non-denominational",
        "name": "Non-denominational Evangelicalism",
        "founded": 1980,
        "parent": "baptists",
        "founder": "Various megachurch pastors",
        "location": "United States (global spread)",
        "adherents": 40000000,
        "color": "#bdc3c7",
        "summary": "Non-denominational churches reject formal denominational ties while typically holding evangelical theology. The movement has produced many of America's largest megachurches and is driven by contemporary worship and practical preaching.",
        "keyDoctrines": ["Biblical authority", "Personal relationship with Jesus", "Contemporary worship", "Seeker-sensitive approach"],
        "scriptureStance": "Bible as authoritative Word of God; generally conservative but flexible",
        "salvationView": "Personal decision to accept Christ; typically eternal security"
    },
    {
        "id": "global-methodist",
        "name": "Global Methodist Church",
        "founded": 2022,
        "parent": "methodism",
        "founder": "Conservative United Methodists",
        "location": "United States",
        "adherents": 500000,
        "color": "#d35400",
        "summary": "The Global Methodist Church formed when theologically conservative congregations left the United Methodist Church primarily over disagreements about LGBTQ+ ordination and same-sex marriage. It holds to traditional Wesleyan sexual ethics.",
        "keyDoctrines": ["Traditional Wesleyan theology", "Traditional marriage definition", "Biblical authority", "Connectionalism"],
        "scriptureStance": "Bible as authoritative; traditional interpretation on sexuality",
        "salvationView": "Wesleyan-Arminian soteriology; grace freely offered to all"
    },

    # ── Pre-Reformation Protest Movements ──
    {
        "id": "waldensians",
        "name": "Waldensians",
        "founded": 1173,
        "parent": "roman-catholicism",
        "founder": "Peter Waldo",
        "location": "Lyon, France / Italian Alps",
        "adherents": 30000,
        "color": "#229954",
        "summary": "Peter Waldo's followers embraced apostolic poverty and lay preaching three centuries before Luther. Persecuted as heretics, the Waldensians survived in Alpine valleys and later joined the Reformed tradition during the Reformation.",
        "keyDoctrines": ["Apostolic poverty", "Lay preaching", "Scripture in the vernacular", "Rejection of purgatory"],
        "scriptureStance": "Bible as sole authority; early vernacular translations",
        "salvationView": "Faith and discipleship in imitation of apostolic poverty"
    },
    {
        "id": "moravian",
        "name": "Moravian Church (Unitas Fratrum)",
        "founded": 1457,
        "parent": "roman-catholicism",
        "founder": "Followers of Jan Hus",
        "location": "Bohemia (Czech Republic)",
        "adherents": 750000,
        "color": "#229954",
        "summary": "The Moravians are the oldest Protestant denomination, predating Luther by 60 years and tracing back to the Hussite movement. Their missionary zeal and prayer life profoundly influenced John Wesley's conversion at a Moravian meeting in 1738.",
        "keyDoctrines": ["Ecumenism", "Missionary zeal", "Prayer emphasis", "Lot as divine guidance (historical)"],
        "scriptureStance": "Bible as rule of faith; emphasis on the life and teachings of Jesus",
        "salvationView": "Grace through faith; heart religion over doctrinal precision"
    },

    # ── Additional Denominations ──
    {
        "id": "plymouth-brethren",
        "name": "Plymouth Brethren",
        "founded": 1825,
        "parent": "anglicanism",
        "founder": "John Nelson Darby",
        "location": "Dublin, Ireland / Plymouth, England",
        "adherents": 1500000,
        "color": "#1e8449",
        "summary": "Darby, a disillusioned Anglican priest, helped found a movement rejecting all denominational structures and clergy-laity distinctions. His invention of dispensationalist theology reshaped evangelical eschatology, influencing the Scofield Bible and Left Behind series.",
        "keyDoctrines": ["Dispensationalism", "Pre-tribulation rapture", "No ordained clergy", "Weekly breaking of bread"],
        "scriptureStance": "Bible as literal, inerrant Word of God; dispensational hermeneutic",
        "salvationView": "Personal faith in Christ; eternal security; dispensational framework of salvation history"
    },
    {
        "id": "rca",
        "name": "Reformed Church in America",
        "founded": 1628,
        "parent": "calvinism",
        "founder": "Dutch Reformed settlers",
        "location": "New Amsterdam (New York City), USA",
        "adherents": 195000,
        "color": "#2ecc71",
        "summary": "The oldest Protestant denomination with continuous existence in North America, founded by Dutch colonists in New Amsterdam. It has maintained a moderate Reformed identity and recently experienced a split as conservative congregations departed.",
        "keyDoctrines": ["Three Forms of Unity", "Reformed worship", "Ecumenical engagement", "Covenant theology"],
        "scriptureStance": "Belgic Confession, Heidelberg Catechism, Canons of Dort",
        "salvationView": "Sovereign grace; covenant theology; Reformed soteriology"
    },
    {
        "id": "cma",
        "name": "Christian and Missionary Alliance",
        "founded": 1887,
        "parent": "calvinism",
        "founder": "A.B. Simpson",
        "location": "New York City, USA",
        "adherents": 6000000,
        "color": "#2ecc71",
        "summary": "A.B. Simpson, a Presbyterian pastor, founded the C&MA to unite Christians around world evangelization. Known for its Four-fold Gospel (Christ as Savior, Sanctifier, Healer, Coming King), it has one of the most extensive missionary networks of any denomination.",
        "keyDoctrines": ["Four-fold Gospel", "World missions emphasis", "Deeper life / sanctification", "Divine healing"],
        "scriptureStance": "Bible as infallible Word of God; evangelical hermeneutic",
        "salvationView": "Personal faith in Christ; sanctification as a deeper work of grace"
    },
    {
        "id": "ucc",
        "name": "United Church of Christ",
        "founded": 1957,
        "parent": "congregationalism",
        "founder": "Merger of Congregational Christian and Evangelical & Reformed churches",
        "location": "United States",
        "adherents": 800000,
        "color": "#229954",
        "summary": "The UCC formed from a merger of four traditions and has been at the forefront of progressive Christianity. It was the first mainline denomination to ordain an openly gay person (1972) and to affirm same-sex marriage (2005).",
        "keyDoctrines": ["God is still speaking", "Congregational autonomy", "Social justice", "Ecumenism", "LGBTQ+ inclusion"],
        "scriptureStance": "Bible as testimony of faith; interpreted through reason and experience",
        "salvationView": "God's inclusive and extravagant welcome; emphasis on justice as salvation"
    },
    {
        "id": "unitarian-universalism",
        "name": "Unitarian Universalism",
        "founded": 1961,
        "parent": "congregationalism",
        "founder": "Merger of Unitarians and Universalists",
        "location": "United States",
        "adherents": 200000,
        "color": "#95a5a6",
        "summary": "UU formed from the merger of the American Unitarian Association (rooted in liberal Congregationalism) and the Universalist Church of America. It has evolved beyond Christianity into a creedless, pluralistic religious community drawing from multiple wisdom traditions.",
        "keyDoctrines": ["Seven Principles", "No creed required", "Religious pluralism", "Individual spiritual search", "Social justice"],
        "scriptureStance": "No single scripture; draws from all world religions, science, and reason",
        "salvationView": "Universal salvation (historical); now focused on human flourishing and justice rather than afterlife"
    },
    {
        "id": "church-of-god-cleveland",
        "name": "Church of God (Cleveland, TN)",
        "founded": 1886,
        "parent": "methodism",
        "founder": "Richard Spurling",
        "location": "Cleveland, Tennessee, USA",
        "adherents": 7000000,
        "color": "#9b59b6",
        "summary": "One of the oldest Pentecostal denominations, originating as a Holiness church in the Appalachian mountains before embracing Spirit baptism. It is among the largest Pentecostal bodies worldwide with strong presence in Latin America and the Caribbean.",
        "keyDoctrines": ["Spirit baptism with tongues", "Sanctification", "Divine healing", "Premillennialism"],
        "scriptureStance": "Bible as inspired, infallible Word of God",
        "salvationView": "Repentance, justification, sanctification, and Spirit baptism"
    },
    {
        "id": "efca",
        "name": "Evangelical Free Church of America",
        "founded": 1950,
        "parent": "lutheranism",
        "founder": "Merger of Swedish and Norwegian-Danish free churches",
        "location": "United States",
        "adherents": 400000,
        "color": "#27ae60",
        "summary": "Rooted in Scandinavian free-church pietism, the EFCA merged two immigrant church bodies in 1950. It is home to Trinity Evangelical Divinity School and emphasizes evangelical essentials with freedom in non-essentials.",
        "keyDoctrines": ["Evangelical essentials", "Congregational governance", "Premillennialism (historically)", "Freedom in non-essentials"],
        "scriptureStance": "Bible as inerrant, authoritative Word of God",
        "salvationView": "Personal faith in Christ; eternal security; evangelical soteriology"
    },
]
